export const WOULD_YOU_RATHER = [
  ['have unlimited snacks but no couch', 'have the perfect couch but no snacks'],
  ['fight one horse-sized duck', 'fight a hundred duck-sized horses'],
  ['live where it is always 4:20pm', 'live where it is always 2am'],
  ['have a rewind button for your life', 'have a pause button for your life'],
  ['talk to animals', 'speak every human language'],
  ['always have a slightly wet sock', 'always have a pebble in your shoe'],
  ['eat only pizza forever', 'never eat pizza again'],
  ['be a famous musician nobody likes', 'be an amazing musician nobody knows'],
  ['explore the deep ocean', 'explore outer space'],
  ['be stuck inside a lava lamp', 'be stuck inside a snow globe'],
  ['have the munchies forever', 'never be hungry again'],
  ['only watch cartoons for the rest of your life', 'only watch documentaries'],
  ['have a cat the size of a dog', 'have a dog the size of a cat'],
  ['fly, but only two feet off the ground', 'be invisible, but only when nobody is looking'],
  ['visit the dinosaurs', 'visit the year 3000'],
  ['live without music', 'live without movies'],
  ['have a laugh that is way too loud', 'have a sneeze that is way too loud'],
  ['always know what time it is', 'always know which way is north'],
  ['eat a whole raw onion', 'drink a cup of pickle juice'],
  ['be the funniest person in the room', 'be the smartest person in the room'],
  ['hear every thought your dog has', 'hear every thought your cat has'],
  ['have a bottomless bag of chips', 'have an ice cream cone that never melts'],
  ['sleep 3 hours and feel fully rested', 'sleep 12 hours and pick your dreams'],
  ['live in a treehouse', 'live on a houseboat'],
  ['speak only in rhymes', 'sing everything you say'],
  ['only use a fork forever', 'only use chopsticks forever'],
  ['find out aliens are real', 'find out ghosts are real'],
  ['have a pet dragon the size of a hamster', 'have a pet hamster the size of a dragon'],
  ['relive the same good day forever', 'never know what tomorrow brings'],
  ['be elite at every video game', 'be elite at every sport'],
  ['only have sweet munchies', 'only have salty munchies'],
  ['have your thoughts show up as subtitles', 'have your life narrated like a nature documentary'],
  ['be a wizard', 'be a superhero'],
  ['have a personal chef', 'have a personal DJ that follows you around'],
  ['always be 10 minutes late', 'always be 20 minutes early'],
  ['have fingers as long as your legs', 'have legs as long as your fingers'],
  ['be able to breathe underwater', 'be able to see in the dark'],
  ['give up your phone for a month', 'give up your bed for a month'],
  ['know every lyric to every song', 'never lose anything ever again'],
  ['have a couch that is also a hot tub', 'have a bed that is also a fridge'],
  ['live in a video game', 'live in a cartoon'],
  ['be a sloth for a day', 'be an eagle for a day'],
  ['never have to do laundry again', 'never have to do dishes again'],
  ['read minds, but you cannot turn it off', 'see the future, but you cannot change it'],
  ['have a theme song that plays when you walk in', 'have a laugh track for everything you say'],
];

export const DEEP_THOUGHTS = [
  'If you could only eat one food for the rest of your life, what is the move?',
  'What is a smell that instantly takes you somewhere?',
  'Is a hot dog a sandwich? Defend it.',
  'What would your ghost haunt?',
  'Do fish know they are wet?',
  'If animals could talk, which one would be the rudest?',
  'What is the most useless talent you have?',
  'What song plays when you walk into a room?',
  'Is cereal a soup?',
  'What is a hill you will die on?',
  'What is the weirdest thing you believed as a kid?',
  'What do dogs dream about?',
  'What is something everyone does that nobody talks about?',
  'Which conspiracy theory would be the funniest if it were true?',
  'You get to add one law. What is it?',
  'What is the best snack combo nobody has tried?',
  'What would be the worst superpower to have?',
  'What are you irrationally scared of?',
  'What is the most overrated food?',
  'If the moon were made of cheese, which cheese?',
  'Your life is a movie. What is the title?',
  'Best thing that happened to you this week?',
  'What movie could you watch a hundred times?',
  'You start a band. What is it called?',
  'What is a word that sounds fake but is real?',
  'Free day, zero responsibilities. What do you do?',
  'We are in a simulation. What glitch proves it?',
  'Master one instrument overnight. Which one?',
  'Last thing that made you laugh until you cried?',
  'Would you go to space if it was one-way?',
  'A food you hated as a kid and love now?',
  'The dumbest way you have ever hurt yourself?',
  'You can be any age for a week. What age?',
  'Go-to karaoke song?',
  'If you had a warning label, what would it say?',
  'Something small that makes your whole day better?',
  'Where would you teleport to right now?',
  'Best pizza topping that sounds wrong?',
  'Is a straw one hole or two?',
  'You can uninvent one thing. What goes?',
  'What would a dog write in a review of you?',
  'Most interesting thing you learned recently?',
  'Which video game world would you actually live in?',
  'What are you obsessed with right now?',
  'A hobby you want to try but have not?',
  'Your pet can text you once. What does it say?',
  'Describe the perfect sesh spot.',
  'What is the best sound in the world?',
  'If you could ask the universe one question, what is it?',
  'Which fictional character would be the worst roommate?',
  'What is the most beautiful place you have ever been?',
  'If colors had flavors, what does blue taste like?',
  'What does your inner monologue sound like?',
  'What is something you changed your mind about?',
  'What would the aliens think of us if they landed today?',
];

export const SKETCH_WORDS = [
  'pizza', 'couch', 'lava lamp', 'taco', 'donut', 'alien', 'ufo', 'cat', 'dog',
  'skateboard', 'sunglasses', 'guitar', 'mushroom', 'rainbow', 'volcano', 'moon',
  'rocket', 'snail', 'cactus', 'banana', 'burger', 'popcorn', 'ice cream',
  'headphones', 'lighter', 'campfire', 'tent', 'hammock', 'sloth', 'turtle',
  'octopus', 'jellyfish', 'shark', 'whale', 'penguin', 'frog', 'owl', 'bee',
  'spider', 'ghost', 'wizard', 'dragon', 'robot', 'pirate', 'snowman',
  'palm tree', 'island', 'waterfall', 'mountain', 'tornado', 'lightning',
  'planet', 'telescope', 'brain', 'eyeball', 'sock', 'crown', 'key', 'castle',
  'bicycle', 'submarine', 'remote', 'hourglass', 'candle', 'toaster',
  'pancakes', 'cereal', 'burrito', 'hot dog', 'fries', 'cookie', 'cupcake',
  'watermelon', 'pineapple', 'avocado', 'cheese', 'noodles', 'sushi', 'cloud',
  'bong', 'joint', 'grinder', 'brownie', 'smoke ring', 'fridge', 'microwave',
  'disco ball', 'traffic cone', 'rubber duck', 'mermaid', 'unicorn', 'vampire',
  'pyramid', 'igloo', 'windmill', 'lighthouse', 'bathtub', 'toilet', 'kite',
];

export function shuffled(arr, rand = Math.random) {
  const a = arr.map((_, i) => i);
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
